# Generated by Django 5.0.6 on 2024-07-15 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triemodel',
            old_name='data',
            new_name='trie_data',
        ),
    ]
